### ISSUE TITLE
Error while running RunExampleCase.m

### ISSUE THREAD

**Issue by RAgneray** [rlober/tcfm#2]
Hello,
I get to the following error when running RunExampleCase.m : 

> ans =

    'running example: joint_positions_feasible'

simulating
t = 0.000
Fast RNE: (c) Peter Corke 2002-2012
Computing objective compatibility and feasibility metrics
Struct contents reference from a non-struct array object.

Error in cvx_global (line 76)
osolvers = cvx___.solvers.list;

Error in cvxprob (line 4)
cvx_global

Error in cvx_begin (line 41)
assignin( 'caller', 'cvx_problem', cvxprob( varargin{:} ) );

Error in computeConstraintAndObjectiveEllipses (line 15)
cvx_begin quiet

Error in QpController/compute_tau (line 71)
                        [obj_el, con_el] = computeConstraintAndObjectiveEllipses(obj.optima,obj.G,obj.h,0);

Error in dynamics (line 19)
    tau = controller.compute_tau(t, q, qd);

Error in Rollout>@(t,y)dynamics(t,y,use_friction) (line 55)
        [t, y] = ode45(@(t,y) dynamics(t,y, use_friction), tspan, y0);

Error in odearguments (line 90)
f0 = feval(ode,t0,y0,args{:});   % ODE15I sets args{1} to yp0.

Error in ode45 (line 115)
    odearguments(FcnHandlesUsed, solver_name, ode, tspan, y0, options, varargin);

Error in Rollout (line 55)
        [t, y] = ode45(@(t,y) dynamics(t,y, use_friction), tspan, y0);

Error in RunExampleCase (line 159)
    raw_data = Rollout(tasks, use_torque_constraint, use_position_constraint, torque_limit, compute_metrics, dt, tend, solver,
    use_ellipsoid_regularization);
 
>> 

Can you tell me what is wrong ?
Thanks for helping

Rémy

**Comment by rlober** [comment]
What version of `cvx` are you using?

Looks like this might be caused by an API change.

Sorry for the delay BTW!

**Comment by RAgneray** [comment]
I'm using the cvx version which on the Github page. 
However, I think I may have the wrong Robotics Toolbox version.
I will try to check with the settings that Mathis Mouchrik sent us by mail.

**Comment by RAgneray** [comment]
Hello,

I successfully achieve to make the RunExampleCase file work by following the settings from Mathias. It appears that the problem did come from Robotics Toolbox version.

But I want to thank you for your help.
Rémy

**Comment by rlober** [comment]
Good to hear. 

Enjoy!
