### ISSUE TITLE
Where is the QP call hidden ?

### ISSUE THREAD

**Issue by vpadois** [rlober/tcfm#3]
Hello,

Looking at the code, I was expecting  to find a call to "compute_tau()" from the QPController class in the "Rollout.m" function but it does not seem to be the case. Where is the main simulation loop run then ?

Best
Vincent

**Comment by rlober** [comment]
Inside of the dynamics callback used by the integration schemes:
https://github.com/rlober/tcfm/blob/master/dynamics.m#L19

Sorry for the delay!
