### ISSUE TITLE
Error while running RunExampleCase.m (error type: vertcat, in QpController.m)

### ISSUE THREAD

**Issue by RAgneray** [rlober/tcfm#4]
Hello,

I was using the RunExampleCase.m file with parameters such as: 
#L.4 `compute_metrics = false;`
#L.6 `use_reduced = true;`
#L.42 `use_ellipsoid_regularization = true;`
in order to use a reduced formulation of the QP control problem.
The following error message appears:

```
Error using vertcat
Dimensions of matrices being concatenated are not consistent.

Error in QpController/solve_qp (line 181)
            obj.E = [obj.E; Ereg];

Error in QpController/compute_tau (line 87)
                tau = obj.solve_qp();

Error in dynamics (line 19)
    tau = controller.compute_tau(t, q, qd);

Error in Rollout>@(t,y)dynamics(t,y,use_friction) (line 62)
        [t, y] = euler_1(@(t,y) dynamics(t,y, use_friction), tspan, y0);

Error in euler_1 (line 11)
    dydt = fn_handle( t(i,1), y(i,:)' );

Error in Rollout (line 62)
        [t, y] = euler_1(@(t,y) dynamics(t,y, use_friction), tspan, y0);

Error in RunExampleCase (line 158)
    raw_data = Rollout(tasks, use_torque_constraint, use_position_constraint, torque_limit, compute_metrics, dt, tend, solver,
    use_ellipsoid_regularization);
```

The source of the error was the fact that this instruction in the file QpController.m wants to concatenate the 6x6 matrix E and the 12x12 matrix Ereg.

To prevent an error message, I replace the instruction in QpController.m (following the equation 4.7 of your thesis):
#L.173: `Ereg = sqrt(reg_weight)*eye(obj.R.n*2);`
by:
`           if use_reduced
                Ereg = sqrt(reg_weight)*eye(obj.R.n);
            else
                Ereg = sqrt(reg_weight)*eye(obj.R.n*2);
            end`

I wanted to know if this replacement is correct or if I made a mistake and misunderstood something.

Regards,
Rémy

**Comment by rlober** [comment]
Hey @RAgneray 

It looks fine to me. Given no external contacts, the dimension of the optimization variable for the reduced case should be equal to `n` the number of joints. 

Just FYI, you may run into more bugs when using the reduced formulation as I switched to the full formulation about half way through coding the lib. Let me know if you run into more issues.
